In [1]:
import json
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
REPLAY_JSON_PATH = PROJECT_ROOT / "replay_parser" / "output" / "parsed_match.json"

with open(REPLAY_JSON_PATH, "r") as f:
    replay_data = json.load(f)

print("Top-level keys:", list(replay_data.keys()))
for key, value in replay_data.items():
    print(f"{key}: {len(value)} entries")

Top-level keys: ['players', 'deaths', 'structures_destroyed', 'patron_events', 'mid_boss_kills', 'rift_captures', 'urn_pickups', 'rejuvenator_claims', 'stat_snapshots']
players: 12 entries
deaths: 120 entries
structures_destroyed: 19 entries
patron_events: 1 entries
mid_boss_kills: 3 entries
rift_captures: 6 entries
urn_pickups: 10 entries
rejuvenator_claims: 18 entries
stat_snapshots: 205 entries

In [2]:
# team for players
players_df = pd.DataFrame(replay_data["players"])
controller_to_team = dict(zip(players_df["controller_index"], players_df["team"]))
print(players_df)

# long format DataFrame
rows = []
for snapshot in replay_data["stat_snapshots"]:
    t = snapshot["game_time_s"]
    for p in snapshot["players"]:
        rows.append({
            "game_time_s": t,
            "controller_index": p["controller_index"],
            "team": p["team"],
            "kills": p["kills"],
            "deaths": p["deaths"],
            "assists": p["assists"],
            "hero_damage": p["hero_damage"],
            "objective_damage": p["objective_damage"],
            "gold_net_worth": p["gold_net_worth"],
        })

snapshots_long = pd.DataFrame(rows)
print(snapshots_long.shape)
snapshots_long.head(10)

    controller_index  pawn_index  team            username
0                  2        3429     2             seiryuu
1                  3        3290     2             Numlegs
2                  4        3568     2  Demui on Twitch :D
3                  5        3495     2                Tech
4                  6          77     3               Docha
5                  7          84     3              Specty
6                  8        3475     2            Seikatsu
7                  9          97     3                Anri
8                 10          98     3               Robin
9                 11          94     3     Little Boy 1945
10                12          89     2              Golova
11                13        3534     3          privativev
(2435, 9)

,game_time_s,controller_index,team,kills,deaths,assists,hero_damage,objective_damage,gold_net_worth
0,15.03125,5,2,0,0,0,0,0,600
1,15.03125,6,3,0,0,0,0,0,600
2,15.03125,10,3,0,0,0,0,0,600
3,15.03125,11,3,0,0,0,0,0,600
4,15.03125,13,3,0,0,0,0,0,600
5,30.03125,5,2,0,0,0,0,0,600
6,30.03125,6,3,0,0,0,0,0,600
7,30.03125,10,3,0,0,0,0,0,600
8,30.03125,11,3,0,0,0,0,0,600
9,30.03125,12,2,0,0,0,0,0,600

In [3]:
team_snapshots = (
    snapshots_long
    .groupby(["game_time_s", "team"], as_index=False)
    .agg({
        "kills": "sum",
        "deaths": "sum",
        "assists": "sum",
        "hero_damage": "sum",
        "objective_damage": "sum",
        "gold_net_worth": "sum",
    })
)

print(team_snapshots.shape)
print(team_snapshots.head(20))

(408, 8)
    game_time_s  team  kills  deaths  assists  hero_damage  objective_damage  \
0      15.03125     2      0       0        0            0                 0
1      15.03125     3      0       0        0            0                 0
2      30.03125     2      0       0        0            0                 0
3      30.03125     3      0       0        0            0                 0
4      45.03125     2      0       0        0            0                 0
5      45.03125     3      0       0        0            0                 0
6      60.03125     2      0       0        0          213                 0
7      60.03125     3      0       0        0          300                 0
8      75.03125     2      0       0        0          887                 0
9      75.03125     3      0       0        0          640                 0
10     90.03125     2      0       0        0         1071                 0
11     90.03125     3      0       0        0          693                 0
12    105.03125     2      0       0        0         1528                24
13    105.03125     3      0       0        0         1126                 0
14    120.03125     2      0       0        0         1833                24
15    120.03125     3      0       0        0         2159                 0
16    135.03125     2      1       0        1         2588                24
17    135.03125     3      0       1        0         2434                 0
18    150.03125     2      1       0        1         3010                24
19    150.03125     3      0       1        0         3391                 0

    gold_net_worth
0              600
1             2400
2             1200
3             2400
4             3600
5             3600
6             3600
7             3600
8             4035
9             4461
10            4468
11            4672
12            4854
13            5499
14            5690
15            5947
16            6638
17            6328
18            7422
19            7036

In [4]:
print(team_snapshots.tail(10))

     game_time_s  team  kills  deaths  assists  hero_damage  objective_damage  \
398  3000.046875     2     55      55      110       292164             21858
399  3000.046875     3     55      55      106       264389             60243
400  3015.046875     2     55      55      110       296633             21858
401  3015.046875     3     55      55      106       267175             64569
402  3030.046875     2     56      57      111       303760             21858
403  3030.046875     3     57      56      116       277521             67049
404  3045.046875     2     56      57      111       303760             21858
405  3045.046875     3     57      56      116       277521             67049
406  3060.046875     2     56      57      111       303760             21858
407  3060.046875     3     57      56      116       277521             67049

     gold_net_worth
398          315532
399          376216
400          315661
401          389154
402          322262
403          391890
404          322262
405          393640
406          322262
407          393640

In [5]:
team_wide = (
    team_snapshots
    .pivot(index="game_time_s", columns="team")
)

team_wide.columns = [
    f"{stat}_team{team}"
    for stat, team in team_wide.columns
]

team_wide = team_wide.reset_index()

print(team_wide.shape)
print(team_wide.head(10))

(204, 13)
   game_time_s  kills_team2  kills_team3  deaths_team2  deaths_team3  \
0     15.03125            0            0             0             0
1     30.03125            0            0             0             0
2     45.03125            0            0             0             0
3     60.03125            0            0             0             0
4     75.03125            0            0             0             0
5     90.03125            0            0             0             0
6    105.03125            0            0             0             0
7    120.03125            0            0             0             0
8    135.03125            1            0             0             1
9    150.03125            1            0             0             1

   assists_team2  assists_team3  hero_damage_team2  hero_damage_team3  \
0              0              0                  0                  0
1              0              0                  0                  0
2              0              0                  0                  0
3              0              0                213                300
4              0              0                887                640
5              0              0               1071                693
6              0              0               1528               1126
7              0              0               1833               2159
8              1              0               2588               2434
9              1              0               3010               3391

   objective_damage_team2  objective_damage_team3  gold_net_worth_team2  \
0                       0                       0                   600
1                       0                       0                  1200
2                       0                       0                  3600
3                       0                       0                  3600
4                       0                       0                  4035
5                       0                       0                  4468
6                      24                       0                  4854
7                      24                       0                  5690
8                      24                       0                  6638
9                      24                       0                  7422

   gold_net_worth_team3
0                  2400
1                  2400
2                  3600
3                  3600
4                  4461
5                  4672
6                  5499
7                  5947
8                  6328
9                  7036

In [6]:
diff_df = pd.DataFrame({
    "game_time_s": team_wide["game_time_s"],

    "kills_diff": (
        team_wide["kills_team2"] -
        team_wide["kills_team3"]
    ),

    "deaths_diff": (
        team_wide["deaths_team2"] -
        team_wide["deaths_team3"]
    ),

    "assists_diff": (
        team_wide["assists_team2"] -
        team_wide["assists_team3"]
    ),

    "hero_damage_diff": (
        team_wide["hero_damage_team2"] -
        team_wide["hero_damage_team3"]
    ),

    "objective_damage_diff": (
        team_wide["objective_damage_team2"] -
        team_wide["objective_damage_team3"]
    ),

    "net_worth_diff": (
        team_wide["gold_net_worth_team2"] -
        team_wide["gold_net_worth_team3"]
    ),
})

print(diff_df.shape)
print(diff_df.head(10))

(204, 7)
   game_time_s  kills_diff  deaths_diff  assists_diff  hero_damage_diff  \
0     15.03125           0            0             0                 0
1     30.03125           0            0             0                 0
2     45.03125           0            0             0                 0
3     60.03125           0            0             0               -87
4     75.03125           0            0             0               247
5     90.03125           0            0             0               378
6    105.03125           0            0             0               402
7    120.03125           0            0             0              -326
8    135.03125           1           -1             1               154
9    150.03125           1           -1             1              -381

   objective_damage_diff  net_worth_diff
0                      0           -1800
1                      0           -1200
2                      0               0
3                      0               0
4                      0            -426
5                      0            -204
6                     24            -645
7                     24            -257
8                     24             310
9                     24             386

In [7]:
# replay event lists into DataFrames
deaths_df = pd.DataFrame(replay_data["deaths"])
structures_df = pd.DataFrame(replay_data["structures_destroyed"])
mid_boss_df = pd.DataFrame(replay_data["mid_boss_kills"])
rejuvenator_df = pd.DataFrame(replay_data["rejuvenator_claims"])

print("Deaths:")
print(deaths_df.head())

print("\nStructures:")
print(structures_df.head())

print("\nMid boss:")
print(mid_boss_df)

print("\nRejuvenator claims:")
print(rejuvenator_df.head(20))

Deaths:
   team  player_index            username  game_time_s  death_duration_s  \
0     3            94     Little Boy 1945   128.187500          8.062500
1     2            89              Golova   151.484375          8.062500
2     3            94     Little Boy 1945   214.687500          8.046875
3     2            92  Demui on Twitch :D   323.109375          8.062500
4     3            94     Little Boy 1945   324.718750          8.062500

  respawn_full_health
0               False
1               False
2               False
3               False
4               False

Structures:
   structure_type  team  destroyed_time_s
0  Tier2Structure     2        670.609375
1  Tier2Structure     3        784.265625
2  Tier2Structure     3        869.343750
3  Tier1Structure     2        903.500000
4  Tier2Structure     2        934.390625

Mid boss:
   killed_time_s
0    1598.609375
1    2563.921875
2    2954.109375

Rejuvenator claims:
    controller_index  team  game_time_s
0                  3     2  1605.250000
1                  2     2  1605.265625
2                 12     2  1605.265625
3                  4     2  1605.296875
4                  5     2  1605.296875
5                  8     2  1605.296875
6                  6     3  2570.281250
7                 10     3  2570.296875
8                  7     3  2570.312500
9                 11     3  2570.312500
10                13     3  2570.312500
11                 9     3  2570.359375
12                 6     3  2960.734375
13                 9     3  2960.734375
14                10     3  2960.765625
15                 7     3  2960.781250
16                11     3  2960.781250
17                13     3  2960.781250

In [8]:
team_mapping = {
    2: "Team0",
    3: "Team1"
}

mid_boss_with_team = []

for _, boss in mid_boss_df.iterrows():
    boss_time = boss["killed_time_s"]

    claims_after_boss = rejuvenator_df[
        (rejuvenator_df["game_time_s"] >= boss_time) &
        (rejuvenator_df["game_time_s"] <= boss_time + 30)
    ].sort_values("game_time_s")

    team_claimed = claims_after_boss.iloc[0]["team"] if len(claims_after_boss) > 0 else None

    mid_boss_with_team.append({
        "killed_time_s": boss_time,
        "team_claimed": team_claimed,
        "perspective_team": team_mapping.get(team_claimed) if team_claimed else None,
    })

mid_boss_df = pd.DataFrame(mid_boss_with_team)
print(mid_boss_df)

   killed_time_s  team_claimed perspective_team
0    1598.609375           2.0            Team0
1    2563.921875           3.0            Team1
2    2954.109375           3.0            Team1

In [9]:
FAST_RESPAWN_THRESHOLD_S = 4.0 # some extra time just in case
REJUV_WINDOW_S = 180  # 3 mins

def team_had_active_rejuv(row, rejuv_df, window_s=REJUV_WINDOW_S):
    team_claims = rejuv_df[rejuv_df["team"] == row["team"]]
    active = team_claims[
        (team_claims["game_time_s"] <= row["game_time_s"]) &
        (row["game_time_s"] <= team_claims["game_time_s"] + window_s)
    ]
    return not active.empty

deaths_df["likely_rejuv_used"] = deaths_df["death_duration_s"] < FAST_RESPAWN_THRESHOLD_S

deaths_df["rejuv_buff_active"] = deaths_df.apply(
    lambda r: team_had_active_rejuv(r, rejuvenator_df), axis=1
)

deaths_df["credit_used"] = deaths_df["likely_rejuv_used"] & deaths_df["rejuv_buff_active"]

rejuv_usage_events = deaths_df[deaths_df["credit_used"]][
    ["team", "player_index", "game_time_s", "death_duration_s"]
]
print(rejuv_usage_events)

     team  player_index  game_time_s  death_duration_s
66      2            78  1705.156250          2.984375
68      2            82  1743.828125          3.000000
71      2            92  1761.109375          2.984375
102     3            94  2729.343750          3.000000
103     3            77  2733.015625          2.984375
113     3           100  2967.468750          3.000000

In [10]:
team_wide = team_wide.rename(columns={
    col: col.replace("_team2", "_team0").replace("_team3", "_team1")
    for col in team_wide.columns
})
print(team_wide.columns.tolist())

['game_time_s', 'kills_team0', 'kills_team1', 'deaths_team0', 'deaths_team1', 'assists_team0', 'assists_team1', 'hero_damage_team0', 'hero_damage_team1', 'objective_damage_team0', 'objective_damage_team1', 'gold_net_worth_team0', 'gold_net_worth_team1']

In [11]:
structures_df["destroying_team"] = structures_df["team"].map({2: 3, 3: 2})  # whoever didn't own it destroyed it
structures_df["perspective_team"] = structures_df["destroying_team"].map(team_mapping)

# cumulative count over time per team
structures_df = structures_df.sort_values("destroyed_time_s")
structures_df["team0_cumulative"] = (structures_df["perspective_team"] == "Team0").cumsum()
structures_df["team1_cumulative"] = (structures_df["perspective_team"] == "Team1").cumsum()
print(structures_df[["destroyed_time_s", "team", "destroying_team", "team0_cumulative", "team1_cumulative"]])

    destroyed_time_s  team  destroying_team  team0_cumulative  \
0         670.609375     2                3                 0
1         784.265625     3                2                 1
2         869.343750     3                2                 2
3         903.500000     2                3                 2
4         934.390625     2                3                 2
5         980.875000     2                3                 2
6        1129.593750     3                2                 3
7        1191.781250     3                2                 4
8        1633.406250     2                3                 4
9        1672.765625     3                2                 5
10       1778.203125     2                3                 5
11       2174.671875     2                3                 5
12       2347.703125     2                3                 5
13       2567.593750     2                3                 5
14       2572.781250     2                3                 5
15       2728.953125     2                3                 5
16       2730.781250     2                3                 5
17       2754.296875     2                3                 5
18       2763.140625     2                3                 5

    team1_cumulative
0                  1
1                  1
2                  1
3                  2
4                  3
5                  4
6                  4
7                  4
8                  5
9                  5
10                 6
11                 7
12                 8
13                 9
14                10
15                11
16                12
17                13
18                14

In [12]:
mid_boss_df = mid_boss_df.sort_values("killed_time_s")
mid_boss_df["team0_cumulative"] = (mid_boss_df["perspective_team"] == "Team0").cumsum()
mid_boss_df["team1_cumulative"] = (mid_boss_df["perspective_team"] == "Team1").cumsum()
print(mid_boss_df)

   killed_time_s  team_claimed perspective_team  team0_cumulative  \
0    1598.609375           2.0            Team0                 1
1    2563.921875           3.0            Team1                 1
2    2954.109375           3.0            Team1                 1

   team1_cumulative
0                 0
1                 1
2                 2

In [13]:
team_wide = team_wide.sort_values("game_time_s")
structures_df = structures_df.sort_values("destroyed_time_s")
mid_boss_df = mid_boss_df.sort_values("killed_time_s")

merged = pd.merge_asof(
    team_wide,
    structures_df[["destroyed_time_s", "team0_cumulative", "team1_cumulative"]].rename(
        columns={"team0_cumulative": "own_objectives_cumulative", "team1_cumulative": "enemy_objectives_cumulative"}
    ),
    left_on="game_time_s",
    right_on="destroyed_time_s",
    direction="backward",
)

merged = pd.merge_asof(
    merged,
    mid_boss_df[["killed_time_s", "team0_cumulative", "team1_cumulative"]].rename(
        columns={"team0_cumulative": "own_mid_boss_claims", "team1_cumulative": "enemy_mid_boss_claims"}
    ),
    left_on="game_time_s",
    right_on="killed_time_s",
    direction="backward",
)

# fill NaNs with 0
for col in ["own_objectives_cumulative", "enemy_objectives_cumulative", "own_mid_boss_claims", "enemy_mid_boss_claims"]:
    merged[col] = merged[col].fillna(0).astype("int64")

merged = merged.drop(columns=["destroyed_time_s", "killed_time_s"])
print(merged.shape)
print(merged.head(10))

(204, 17)
   game_time_s  kills_team0  kills_team1  deaths_team0  deaths_team1  \
0     15.03125            0            0             0             0
1     30.03125            0            0             0             0
2     45.03125            0            0             0             0
3     60.03125            0            0             0             0
4     75.03125            0            0             0             0
5     90.03125            0            0             0             0
6    105.03125            0            0             0             0
7    120.03125            0            0             0             0
8    135.03125            1            0             0             1
9    150.03125            1            0             0             1

   assists_team0  assists_team1  hero_damage_team0  hero_damage_team1  \
0              0              0                  0                  0
1              0              0                  0                  0
2              0              0                  0                  0
3              0              0                213                300
4              0              0                887                640
5              0              0               1071                693
6              0              0               1528               1126
7              0              0               1833               2159
8              1              0               2588               2434
9              1              0               3010               3391

   objective_damage_team0  objective_damage_team1  gold_net_worth_team0  \
0                       0                       0                   600
1                       0                       0                  1200
2                       0                       0                  3600
3                       0                       0                  3600
4                       0                       0                  4035
5                       0                       0                  4468
6                      24                       0                  4854
7                      24                       0                  5690
8                      24                       0                  6638
9                      24                       0                  7422

   gold_net_worth_team1  own_objectives_cumulative  \
0                  2400                          0
1                  2400                          0
2                  3600                          0
3                  3600                          0
4                  4461                          0
5                  4672                          0
6                  5499                          0
7                  5947                          0
8                  6328                          0
9                  7036                          0

   enemy_objectives_cumulative  own_mid_boss_claims  enemy_mid_boss_claims
0                            0                    0                      0
1                            0                    0                      0
2                            0                    0                      0
3                            0                    0                      0
4                            0                    0                      0
5                            0                    0                      0
6                            0                    0                      0
7                            0                    0                      0
8                            0                    0                      0
9                            0                    0                      0

In [14]:
merged['net_worth_diff'] = merged['gold_net_worth_team0'] - merged['gold_net_worth_team1']
merged['kills_diff'] = merged['kills_team0'] - merged['kills_team1']
merged['deaths_diff'] = merged['deaths_team0'] - merged['deaths_team1']
merged['damage_diff'] = merged['hero_damage_team0'] - merged['hero_damage_team1']
merged['objectives_diff'] = merged['own_objectives_cumulative'] - merged['enemy_objectives_cumulative']
merged['deaths_cumulative_diff'] = merged['deaths_team0'] - merged['deaths_team1']
merged['mid_boss_diff'] = merged['own_mid_boss_claims'] - merged['enemy_mid_boss_claims']

feature_cols = [
    'own_deaths_cumulative', 'enemy_deaths_cumulative',
    'own_objectives_cumulative', 'enemy_objectives_cumulative',
    'own_mid_boss_claims', 'enemy_mid_boss_claims',
    'net_worth_diff', 'kills_diff', 'deaths_diff', 'damage_diff',
    'objectives_diff', 'deaths_cumulative_diff', 'mid_boss_diff'
]

# rename deaths_team0/1 to match training column names for cumulative deaths
merged['own_deaths_cumulative'] = merged['deaths_team0']
merged['enemy_deaths_cumulative'] = merged['deaths_team1']

print(merged[feature_cols].shape)
merged[feature_cols].head(10)

(204, 13)

,own_deaths_cumulative,enemy_deaths_cumulative,own_objectives_cumulative,enemy_objectives_cumulative,own_mid_boss_claims,enemy_mid_boss_claims,net_worth_diff,kills_diff,deaths_diff,damage_diff,objectives_diff,deaths_cumulative_diff,mid_boss_diff
0,0,0,0,0,0,0,-1800,0,0,0,0,0,0
1,0,0,0,0,0,0,-1200,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,-87,0,0,0
4,0,0,0,0,0,0,-426,0,0,247,0,0,0
5,0,0,0,0,0,0,-204,0,0,378,0,0,0
6,0,0,0,0,0,0,-645,0,0,402,0,0,0
7,0,0,0,0,0,0,-257,0,0,-326,0,0,0
8,0,1,0,0,0,0,310,1,-1,154,0,-1,0
9,0,1,0,0,0,0,386,1,-1,-381,0,-1,0

In [15]:
import torch
import torch.nn as nn

class WinProbabilityLSTM(nn.Module):
    def __init__(self, input_size, hidden_size=32, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
        )
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        logits = self.fc(lstm_out)
        return logits.squeeze(-1)

MODEL_PATH = PROJECT_ROOT / "models" / "win_probability_lstm_v1.pt"
checkpoint = torch.load(MODEL_PATH, map_location="cpu")

trained_feature_cols = checkpoint["feature_cols"]
print("Trained feature order:", trained_feature_cols)
print("Your feature order:   ", feature_cols)
assert trained_feature_cols == feature_cols, "Column order mismatch — reorder before proceeding!"

model = WinProbabilityLSTM(
    input_size=checkpoint["input_size"],
    hidden_size=checkpoint["hidden_size"],
)
model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

feature_array = merged[feature_cols].values.astype("float32")
input_tensor = torch.tensor(feature_array).unsqueeze(0)  # [1, seq_len, input_size]
print("Input shape:", input_tensor.shape)

with torch.no_grad():
    logits = model(input_tensor)
    win_probs = torch.sigmoid(logits).squeeze(0).numpy()

merged["win_prob_team0"] = win_probs
print(merged[["game_time_s", "win_prob_team0"]])

Trained feature order: ['own_deaths_cumulative', 'enemy_deaths_cumulative', 'own_objectives_cumulative', 'enemy_objectives_cumulative', 'own_mid_boss_claims', 'enemy_mid_boss_claims', 'net_worth_diff', 'kills_diff', 'deaths_diff', 'damage_diff', 'objectives_diff', 'deaths_cumulative_diff', 'mid_boss_diff']
Your feature order:    ['own_deaths_cumulative', 'enemy_deaths_cumulative', 'own_objectives_cumulative', 'enemy_objectives_cumulative', 'own_mid_boss_claims', 'enemy_mid_boss_claims', 'net_worth_diff', 'kills_diff', 'deaths_diff', 'damage_diff', 'objectives_diff', 'deaths_cumulative_diff', 'mid_boss_diff']
Input shape: torch.Size([1, 204, 13])
     game_time_s  win_prob_team0
0      15.031250        0.188125
1      30.031250        0.177117
2      45.031250        0.352302
3      60.031250        0.416144
4      75.031250        0.401653
..           ...             ...
199  3000.046875        0.326755
200  3015.046875        0.303769
201  3030.046875        0.339255
202  3045.046875        0.339255
203  3060.046875        0.339255

[204 rows x 2 columns]

In [16]:
merged["win_prob_delta"] = merged["win_prob_team0"].diff()

# flag meaningful swings — aka when an event happens to de/increase the win prob
SWING_THRESHOLD = 0.05

swings = merged[merged["win_prob_delta"].abs() >= SWING_THRESHOLD][
    ["game_time_s", "win_prob_team0", "win_prob_delta"]
]
print(f"Found {len(swings)} swings of {SWING_THRESHOLD}+ magnitude:")
print(swings)

print("\nDelta distribution (to help pick a good threshold):")
print(merged["win_prob_delta"].describe())

Found 43 swings of 0.05+ magnitude:
     game_time_s  win_prob_team0  win_prob_delta
2      45.031250        0.352302        0.175185
3      60.031250        0.416144        0.063842
6     105.031250        0.327984       -0.079169
7     120.031250        0.245233       -0.082751
8     135.031250        0.520308        0.275075
9     150.031250        0.664794        0.144485
10    165.031250        0.458741       -0.206052
11    180.031250        0.272689       -0.186052
12    195.031250        0.159037       -0.113653
14    225.031250        0.596993        0.432030
15    240.046875        0.651483        0.054490
16    255.046875        0.576222       -0.075261
17    270.046875        0.388541       -0.187681
18    285.046875        0.457748        0.069207
19    300.046875        0.797832        0.340083
30    465.046875        0.756987        0.057520
31    480.046875        0.659271       -0.097716
32    495.046875        0.535890       -0.123381
34    525.046875        0.621469        0.099610
35    540.046875        0.748952        0.127483
42    645.046875        0.651213       -0.104626
44    675.046875        0.462300       -0.184525
45    690.046875        0.686870        0.224570
46    705.046875        0.746901        0.060031
51    780.046875        0.755839       -0.069159
59    900.046875        0.717709       -0.077745
65    990.046875        0.642658       -0.103032
67   1020.046875        0.715583        0.061244
70   1065.046875        0.610780       -0.106906
71   1080.046875        0.739011        0.128231
74   1125.046875        0.837401        0.119692
77   1170.046875        0.755840       -0.077859
85   1290.046875        0.717710       -0.077552
86   1305.046875        0.810446        0.092736
131  1980.046875        0.755580       -0.078307
133  2010.046875        0.377011       -0.378480
149  2250.046875        0.468698        0.084945
150  2265.046875        0.709040        0.240342
151  2280.046875        0.617163       -0.091877
152  2295.046875        0.440960       -0.176203
154  2325.046875        0.598207        0.118301
156  2355.046875        0.368766       -0.208031
167  2520.046875        0.300369       -0.068393

Delta distribution (to help pick a good threshold):
count    203.000000
mean       0.000744
std        0.076714
min       -0.378480
25%       -0.010090
50%        0.000000
75%        0.010931
max        0.432030
Name: win_prob_delta, dtype: float64

In [17]:
# smoothing the noise, esp in early game

merged["win_prob_smoothed"] = merged["win_prob_team0"].rolling(window=3, center=True, min_periods=1).mean()
merged["win_prob_delta_smoothed"] = merged["win_prob_smoothed"].diff()

swings_smoothed = merged[merged["win_prob_delta_smoothed"].abs() >= SWING_THRESHOLD][
    ["game_time_s", "win_prob_smoothed", "win_prob_delta_smoothed"]
]
print(f"Found {len(swings_smoothed)} smoothed swings of {SWING_THRESHOLD}+ magnitude:")
print(swings_smoothed)

Found 31 smoothed swings of 0.05+ magnitude:
     game_time_s  win_prob_smoothed  win_prob_delta_smoothed
1      30.031250           0.239181                 0.056560
2      45.031250           0.315188                 0.076006
3      60.031250           0.390033                 0.074845
6     105.031250           0.326790                -0.052140
8     135.031250           0.476778                 0.112270
9     150.031250           0.547948                 0.071169
10    165.031250           0.465408                -0.082540
11    180.031250           0.296822                -0.168586
12    195.031250           0.198896                -0.097926
13    210.031250           0.306997                 0.108101
14    225.031250           0.471146                 0.164149
15    240.046875           0.608233                 0.137086
16    255.046875           0.538749                -0.069484
17    270.046875           0.474171                -0.064578
18    285.046875           0.548040                 0.073870
19    300.046875           0.679055                 0.131015
20    315.046875           0.775844                 0.096788
31    480.046875           0.650716                -0.054525
32    495.046875           0.572340                -0.078376
34    525.046875           0.630760                 0.071021
35    540.046875           0.708142                 0.077382
43    660.046875           0.586779                -0.097846
46    705.046875           0.729761                 0.097738
132  1995.046875           0.629361                -0.152292
133  2010.046875           0.501256                -0.128104
134  2025.046875           0.373162                -0.128094
149  2250.046875           0.520497                 0.108072
150  2265.046875           0.598301                 0.077803
152  2295.046875           0.512676                -0.076378
156  2355.046875           0.451002                -0.063588
157  2370.046875           0.398966                -0.052036

In [18]:
urn_df = pd.DataFrame(replay_data["urn_pickups"])
rift_df = pd.DataFrame(replay_data["rift_captures"])

print(urn_df.head())
print(rift_df.head())

   spawn_time_s  pickup_time_s
0     630.03125     681.796875
1     930.03125     942.671875
2    1230.03125    1251.968750
3    1530.03125    1766.250000
4    1830.03125    1842.828125
   cashin_time_s  spawn_time_s
0     744.093750    724.000000
1    1148.296875   1128.203125
2    1659.015625   1638.921875
3    1984.687500   1964.593750
4    2520.796875   2500.703125

In [19]:
def infer_team_from_net_worth_spike(event_time, window_s=5):
    before = merged[merged["game_time_s"] <= event_time].tail(1)
    after = merged[merged["game_time_s"] >= event_time].head(1)

    if before.empty or after.empty:
        return None

    net_worth_diff_before = before["net_worth_diff"].values[0]
    net_worth_diff_after = after["net_worth_diff"].values[0]
    delta = net_worth_diff_after - net_worth_diff_before

    # positive delta = team0 (team 2) gained relatively -> team0 likely claimed it
    # negative delta = team1 (team 3) gained relatively -> team1 likely claimed it
    if delta > 0:
        return "Team0"
    elif delta < 0:
        return "Team1"
    return None

rift_df["inferred_team"] = rift_df["cashin_time_s"].apply(infer_team_from_net_worth_spike)
urn_df["inferred_team"] = urn_df["pickup_time_s"].apply(infer_team_from_net_worth_spike)

print(rift_df[["cashin_time_s", "inferred_team"]])
print(urn_df[["pickup_time_s", "inferred_team"]])

   cashin_time_s inferred_team
0     744.093750         Team0
1    1148.296875         Team1
2    1659.015625         Team1
3    1984.687500         Team1
4    2520.796875         Team1
5    2986.015625         Team1
   pickup_time_s inferred_team
0     681.796875         Team0
1     942.671875         Team0
2    1251.968750         Team1
3    1766.250000         Team0
4    1842.828125         Team0
5    2333.796875         Team1
6    2349.875000         Team1
7    2366.312500         Team0
8    2568.265625         Team1
9    2905.218750         Team1

In [20]:
pawn_to_username = {
    p["pawn_index"]: p["username"]
    for p in replay_data["players"]
    if p.get("pawn_index") is not None
}
print(pawn_to_username)

{3429: 'seiryuu', 3290: 'Numlegs', 3568: 'Demui on Twitch :D', 3495: 'Tech', 77: 'Docha', 84: 'Specty', 3475: 'Seikatsu', 97: 'Anri', 98: 'Robin', 94: 'Little Boy 1945', 89: 'Golova', 3534: 'privativev'}

In [22]:
print(deaths_df[["player_index", "username"]].drop_duplicates())
print("\nDeaths with missing username:", deaths_df["username"].isna().sum())

    player_index            username
0             94     Little Boy 1945
1             89              Golova
3             92  Demui on Twitch :D
5             97                Anri
6             82             seiryuu
9             85            Seikatsu
13            77               Docha
17           100          privativev
24            84              Specty
31            98               Robin
46            80                Tech
50            78             Numlegs

Deaths with missing username: 0

In [27]:
def find_nearest_events(swing_time, lookback_s=30):
    events = []

    nearby_deaths = deaths_df[
        (deaths_df["game_time_s"] <= swing_time) &
        (deaths_df["game_time_s"] >= swing_time - lookback_s)
    ]
    for _, d in nearby_deaths.iterrows():
        events.append({
            "type": "death",
            "time": d["game_time_s"],
            "team": d["team"],
            "player_index": d["player_index"],
            "username": d["username"],
        })

    nearby_structures = structures_df[
        (structures_df["destroyed_time_s"] <= swing_time) &
        (structures_df["destroyed_time_s"] >= swing_time - lookback_s)
    ]
    for _, s in nearby_structures.iterrows():
        events.append({"type": "structure", "time": s["destroyed_time_s"], "team": s["team"], "structure_type": s["structure_type"]})

    nearby_midboss = mid_boss_df[
        (mid_boss_df["killed_time_s"] <= swing_time) &
        (mid_boss_df["killed_time_s"] >= swing_time - lookback_s)
    ]
    for _, mb in nearby_midboss.iterrows():
        events.append({"type": "mid_boss", "time": mb["killed_time_s"], "team_claimed": mb["team_claimed"]})

    nearby_rejuv = rejuvenator_df[
        (rejuvenator_df["game_time_s"] <= swing_time) &
        (rejuvenator_df["game_time_s"] >= swing_time - lookback_s)
    ]
    for _, r in nearby_rejuv.iterrows():
        events.append({"type": "rejuv_claim", "time": r["game_time_s"], "team": r["team"]})

    nearby_urns = urn_df[
        (urn_df["pickup_time_s"] <= swing_time) &
        (urn_df["pickup_time_s"] >= swing_time - lookback_s)
    ]
    for _, u in nearby_urns.iterrows():
        events.append({"type": "urn_pickup", "time": u["pickup_time_s"], "team": u["inferred_team"]})

    nearby_rifts = rift_df[
        (rift_df["cashin_time_s"] <= swing_time) &
        (rift_df["cashin_time_s"] >= swing_time - lookback_s)
    ]
    for _, r in nearby_rifts.iterrows():
        events.append({"type": "rift_capture", "time": r["cashin_time_s"], "team": r["inferred_team"]})

    return sorted(events, key=lambda e: e["time"], reverse=True)


attributed_swings = []

for _, row in swings_smoothed.iterrows():
    swing_time = row["game_time_s"]
    delta = row["win_prob_delta_smoothed"]
    events = find_nearest_events(swing_time)

    attributed_swings.append({
        "swing_time_s": swing_time,
        "win_prob_after": row["win_prob_smoothed"],
        "delta": delta,
        "direction": "team0_favored" if delta > 0 else "team1_favored",
        "nearest_events": events,
    })

for s in attributed_swings:
    print(f"\n--- Swing at {s['swing_time_s']:.1f}s ({s['direction']}, Δ={s['delta']:+.3f}) ---")
    if not s["nearest_events"]:
        print("  No nearby events found within lookback window")
    for e in s["nearest_events"]:
        print(f"  {e}")

--- Swing at 30.0s (team0_favored, Δ=+0.057) ---
  No nearby events found within lookback window

--- Swing at 45.0s (team0_favored, Δ=+0.076) ---
  No nearby events found within lookback window

--- Swing at 60.0s (team0_favored, Δ=+0.075) ---
  No nearby events found within lookback window

--- Swing at 105.0s (team1_favored, Δ=-0.052) ---
  No nearby events found within lookback window

--- Swing at 135.0s (team0_favored, Δ=+0.112) ---
  {'type': 'death', 'time': 128.1875, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}

--- Swing at 150.0s (team0_favored, Δ=+0.071) ---
  {'type': 'death', 'time': 128.1875, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}

--- Swing at 165.0s (team1_favored, Δ=-0.083) ---
  {'type': 'death', 'time': 151.484375, 'team': 2, 'player_index': 89, 'username': 'Golova'}

--- Swing at 180.0s (team1_favored, Δ=-0.169) ---
  {'type': 'death', 'time': 151.484375, 'team': 2, 'player_index': 89, 'username': 'Golova'}

--- Swing at 195.0s (team1_favored, Δ=-0.098) ---
  No nearby events found within lookback window

--- Swing at 210.0s (team0_favored, Δ=+0.108) ---
  No nearby events found within lookback window

--- Swing at 225.0s (team0_favored, Δ=+0.164) ---
  {'type': 'death', 'time': 214.6875, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}

--- Swing at 240.0s (team0_favored, Δ=+0.137) ---
  {'type': 'death', 'time': 214.6875, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}

--- Swing at 255.0s (team1_favored, Δ=-0.069) ---
  No nearby events found within lookback window

--- Swing at 270.0s (team1_favored, Δ=-0.065) ---
  No nearby events found within lookback window

--- Swing at 285.0s (team0_favored, Δ=+0.074) ---
  No nearby events found within lookback window

--- Swing at 300.0s (team0_favored, Δ=+0.131) ---
  No nearby events found within lookback window

--- Swing at 315.0s (team0_favored, Δ=+0.097) ---
  No nearby events found within lookback window

--- Swing at 480.0s (team1_favored, Δ=-0.055) ---
  {'type': 'death', 'time': 476.5, 'team': 2, 'player_index': 92, 'username': 'Demui on Twitch :D'}
  {'type': 'death', 'time': 468.46875, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}

--- Swing at 495.0s (team1_favored, Δ=-0.078) ---
  {'type': 'death', 'time': 476.5, 'team': 2, 'player_index': 92, 'username': 'Demui on Twitch :D'}
  {'type': 'death', 'time': 468.46875, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}

--- Swing at 525.0s (team0_favored, Δ=+0.071) ---
  {'type': 'death', 'time': 510.578125, 'team': 3, 'player_index': 77, 'username': 'Docha'}
  {'type': 'death', 'time': 509.765625, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}
  {'type': 'death', 'time': 505.140625, 'team': 2, 'player_index': 82, 'username': 'seiryuu'}

--- Swing at 540.0s (team0_favored, Δ=+0.077) ---
  {'type': 'death', 'time': 510.578125, 'team': 3, 'player_index': 77, 'username': 'Docha'}

--- Swing at 660.0s (team1_favored, Δ=-0.098) ---
  {'type': 'death', 'time': 647.625, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}
  {'type': 'death', 'time': 644.765625, 'team': 2, 'player_index': 89, 'username': 'Golova'}
  {'type': 'death', 'time': 637.390625, 'team': 2, 'player_index': 92, 'username': 'Demui on Twitch :D'}
  {'type': 'death', 'time': 634.65625, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}

--- Swing at 705.0s (team0_favored, Δ=+0.098) ---
  {'type': 'urn_pickup', 'time': 681.796875, 'team': 'Team0'}
  {'type': 'death', 'time': 679.796875, 'team': 3, 'player_index': 77, 'username': 'Docha'}

--- Swing at 1995.0s (team1_favored, Δ=-0.152) ---
  {'type': 'rift_capture', 'time': 1984.6875, 'team': 'Team1'}
  {'type': 'death', 'time': 1977.109375, 'team': 2, 'player_index': 82, 'username': 'seiryuu'}
  {'type': 'death', 'time': 1969.9375, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}
  {'type': 'death', 'time': 1966.8125, 'team': 2, 'player_index': 92, 'username': 'Demui on Twitch :D'}

--- Swing at 2010.0s (team1_favored, Δ=-0.128) ---
  {'type': 'rift_capture', 'time': 1984.6875, 'team': 'Team1'}

--- Swing at 2025.0s (team1_favored, Δ=-0.128) ---
  No nearby events found within lookback window

--- Swing at 2250.0s (team0_favored, Δ=+0.108) ---
  {'type': 'death', 'time': 2242.65625, 'team': 3, 'player_index': 100, 'username': 'privativev'}
  {'type': 'death', 'time': 2241.53125, 'team': 3, 'player_index': 98, 'username': 'Robin'}
  {'type': 'death', 'time': 2234.703125, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}
  {'type': 'death', 'time': 2231.578125, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}
  {'type': 'death', 'time': 2225.140625, 'team': 2, 'player_index': 82, 'username': 'seiryuu'}

--- Swing at 2265.0s (team0_favored, Δ=+0.078) ---
  {'type': 'death', 'time': 2263.6875, 'team': 3, 'player_index': 97, 'username': 'Anri'}
  {'type': 'death', 'time': 2242.65625, 'team': 3, 'player_index': 100, 'username': 'privativev'}
  {'type': 'death', 'time': 2241.53125, 'team': 3, 'player_index': 98, 'username': 'Robin'}

--- Swing at 2295.0s (team1_favored, Δ=-0.076) ---
  {'type': 'death', 'time': 2279.9375, 'team': 2, 'player_index': 89, 'username': 'Golova'}

--- Swing at 2355.0s (team1_favored, Δ=-0.064) ---
  {'type': 'death', 'time': 2353.84375, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}
  {'type': 'urn_pickup', 'time': 2349.875, 'team': 'Team1'}
  {'type': 'structure', 'time': 2347.703125, 'team': 2, 'structure_type': 'Tier1Structure'}
  {'type': 'urn_pickup', 'time': 2333.796875, 'team': 'Team1'}

--- Swing at 2370.0s (team1_favored, Δ=-0.052) ---
  {'type': 'urn_pickup', 'time': 2366.3125, 'team': 'Team0'}
  {'type': 'death', 'time': 2365.453125, 'team': 2, 'player_index': 82, 'username': 'seiryuu'}
  {'type': 'death', 'time': 2360.96875, 'team': 3, 'player_index': 84, 'username': 'Specty'}
  {'type': 'death', 'time': 2358.109375, 'team': 3, 'player_index': 94, 'username': 'Little Boy 1945'}
  {'type': 'death', 'time': 2353.84375, 'team': 2, 'player_index': 85, 'username': 'Seikatsu'}
  {'type': 'urn_pickup', 'time': 2349.875, 'team': 'Team1'}
  {'type': 'structure', 'time': 2347.703125, 'team': 2, 'structure_type': 'Tier1Structure'}

In [37]:
def get_user_team(username, players_df, team_mapping):
    match = players_df[players_df["username"] == username]
    if match.empty:
        raise ValueError(f"No player found with username '{username}'")
    raw_team = match.iloc[0]["team"]  # this is 2 or 3 (Deadlock's raw team id)
    perspective_team = team_mapping[raw_team]  # "Team0" or "Team1"
    return 0 if perspective_team == "Team0" else 1

# let the user pick their name
USER_USERNAME = "seiryuu" 
USER_TEAM = get_user_team(USER_USERNAME, players_df, team_mapping)
print(f"Viewing report as {USER_USERNAME}, team {USER_TEAM}")

Viewing report as seiryuu, team 0

In [40]:
# early drafttttt

def format_time(seconds):
    m = int(seconds // 60)
    s = int(seconds % 60)
    return f"{m}:{s:02d}"

def event_to_phrase(event, user_team):
    is_user_team = event.get("team") == user_team

    if event["type"] == "death":
        who = event["username"]
        possessive = "your teammate" if is_user_team else "the enemy"
        return f"{possessive} {who} died at {format_time(event['time'])}"

    if event["type"] == "structure":
        side = "your team" if is_user_team else "the enemy"
        verb = "lost" if is_user_team else "destroyed"
        return f"{side} {verb} a {event['structure_type']} at {format_time(event['time'])}"

    if event["type"] == "mid_boss":
        claimer = "your team" if event["team_claimed"] == user_team else "the enemy"
        return f"{claimer} claimed the Mid Boss Rejuvenator at {format_time(event['time'])}"

    if event["type"] == "urn_pickup":
        claimer = "your team" if event["team"] == user_team else "the enemy"
        return f"{claimer} secured the Urn at {format_time(event['time'])}"

    if event["type"] == "rift_capture":
        claimer = "your team" if event["team"] == user_team else "the enemy"
        return f"{claimer} cashed in the Rift at {format_time(event['time'])}"

    return None

def get_win_prob_pct(raw_win_prob_team0, user_team):
    raw = raw_win_prob_team0 if user_team == 0 else (1 - raw_win_prob_team0)
    return raw * 100

GAP_THRESHOLD_S = 300  # bridge silences longer than 5 minutes with a checkpoint line

def generate_narrative(attributed_swings, user_team, merged_df):
    lines = []
    seen_events = set()

    prev_time = merged_df["game_time_s"].min()

    for s in attributed_swings:
        swing_time = s["swing_time_s"]

        # bridge long gaps with a checkpoint describing the quiet stretch
        gap = swing_time - prev_time
        if gap >= GAP_THRESHOLD_S:
            gap_slice = merged_df[
                (merged_df["game_time_s"] >= prev_time) &
                (merged_df["game_time_s"] <= swing_time)
            ]
            probs = gap_slice["win_prob_smoothed"].apply(lambda p: get_win_prob_pct(p, user_team))
            avg_prob = probs.mean()
            state = "led" if avg_prob >= 50 else "trailed"
            lines.append(
                f"From {format_time(prev_time)} to {format_time(swing_time)}, "
                f"your team {state} comfortably (around {avg_prob:.0f}% win chance) with no major swings."
            )

        delta_pct = abs(s["delta"]) * 100
        prob_pct = get_win_prob_pct(s["win_prob_after"], user_team)
        favored = "boosted your win chance" if (s["direction"] == "team0_favored") == (user_team == 0) else "hurt your win chance"

        event_phrase = None
        for e in s["nearest_events"]:
            key = (e["type"], e["time"])
            if key not in seen_events:
                event_phrase = event_to_phrase(e, user_team)
                seen_events.add(key)
                break

        if event_phrase:
            lines.append(f"At {format_time(swing_time)}, {event_phrase}, which {favored} by {delta_pct:.0f}% (now {prob_pct:.0f}% win chance).")
        else:
            lines.append(f"By {format_time(swing_time)}, a natural farming/economy difference {favored} by {delta_pct:.0f}% (now {prob_pct:.0f}% win chance).")

        prev_time = swing_time

    return lines

narrative_lines = generate_narrative(attributed_swings, USER_TEAM, merged)
for line in narrative_lines:
    print(line)

By 0:30, a natural farming/economy difference boosted your win chance by 6% (now 24% win chance).
By 0:45, a natural farming/economy difference boosted your win chance by 8% (now 32% win chance).
By 1:00, a natural farming/economy difference boosted your win chance by 7% (now 39% win chance).
By 1:45, a natural farming/economy difference hurt your win chance by 5% (now 33% win chance).
At 2:15, the enemy Little Boy 1945 died at 2:08, which boosted your win chance by 11% (now 48% win chance).
By 2:30, a natural farming/economy difference boosted your win chance by 7% (now 55% win chance).
At 2:45, the enemy Golova died at 2:31, which hurt your win chance by 8% (now 47% win chance).
By 3:00, a natural farming/economy difference hurt your win chance by 17% (now 30% win chance).
By 3:15, a natural farming/economy difference hurt your win chance by 10% (now 20% win chance).
By 3:30, a natural farming/economy difference boosted your win chance by 11% (now 31% win chance).
At 3:45, the enemy Little Boy 1945 died at 3:34, which boosted your win chance by 16% (now 47% win chance).
By 4:00, a natural farming/economy difference boosted your win chance by 14% (now 61% win chance).
By 4:15, a natural farming/economy difference hurt your win chance by 7% (now 54% win chance).
By 4:30, a natural farming/economy difference hurt your win chance by 6% (now 47% win chance).
By 4:45, a natural farming/economy difference boosted your win chance by 7% (now 55% win chance).
By 5:00, a natural farming/economy difference boosted your win chance by 13% (now 68% win chance).
By 5:15, a natural farming/economy difference boosted your win chance by 10% (now 78% win chance).
At 8:00, the enemy Demui on Twitch :D died at 7:56, which hurt your win chance by 5% (now 65% win chance).
At 8:15, the enemy Seikatsu died at 7:48, which hurt your win chance by 8% (now 57% win chance).
At 8:45, the enemy Docha died at 8:30, which boosted your win chance by 7% (now 63% win chance).
By 9:00, a natural farming/economy difference boosted your win chance by 8% (now 71% win chance).
At 11:00, the enemy Little Boy 1945 died at 10:47, which hurt your win chance by 10% (now 59% win chance).
At 11:45, the enemy secured the Urn at 11:21, which boosted your win chance by 10% (now 73% win chance).
From 11:45 to 33:15, your team led comfortably (around 79% win chance) with no major swings.
At 33:15, the enemy cashed in the Rift at 33:04, which hurt your win chance by 15% (now 63% win chance).
By 33:30, a natural farming/economy difference hurt your win chance by 13% (now 50% win chance).
By 33:45, a natural farming/economy difference hurt your win chance by 13% (now 37% win chance).
At 37:30, the enemy privativev died at 37:22, which boosted your win chance by 11% (now 52% win chance).
At 37:45, the enemy Anri died at 37:43, which boosted your win chance by 8% (now 60% win chance).
At 38:15, the enemy Golova died at 37:59, which hurt your win chance by 8% (now 51% win chance).
At 39:15, the enemy Seikatsu died at 39:13, which hurt your win chance by 6% (now 45% win chance).
At 39:30, the enemy secured the Urn at 39:26, which hurt your win chance by 5% (now 40% win chance).